pipeline:

  build:
    image: docker:18.09.0
    secrets:
      - npm_auth_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - NPM_AUTH_USERNAME=asl
    commands:
      - docker build --build-arg NPM_AUTH_USERNAME=$${NPM_AUTH_USERNAME} --build-arg NPM_AUTH_TOKEN=$${NPM_AUTH_TOKEN} -t asl-notifications .

  push_ecr:
    image: docker:18.09.0
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - AWSCLI_IMAGE=quay.io/ukhomeofficedigital/aws-cli:latest
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - REGISTRY_URL=340268328991.dkr.ecr.eu-west-2.amazonaws.com/asl/notifications
    commands:
      - authtoken=$(docker run --rm -e "AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY}" -e "AWS_DEFAULT_REGION=$${AWS_DEFAULT_REGION}" $${AWSCLI_IMAGE} ecr get-login --no-include-email | cut -d' ' -f6)
      - docker login -u AWS -p $authtoken $${REGISTRY_URL}}
      - docker tag asl-notifications $${REGISTRY_URL}:$${DRONE_COMMIT_SHA}
      - docker push $${REGISTRY_URL}:$${DRONE_COMMIT_SHA}

  push_quay:
    image: docker:18.09.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-notifications quay.io/ukhomeofficedigital/asl-notifications:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-notifications:$${DRONE_COMMIT_SHA}